### PR TITLE
bug 1134587

### PR DESCRIPTION
**Pull request by trevorhobson**
- Add support for CompatGeckoFxOS to scraper

### CODE REVIEW

**Comment by trevorhobson** [comment]
Can you assist me with the failing test please.

**Comment by jwhitlock** [comment]
I'm sorry, I didn't look at the source for this template, I thought it was like the "don't do much" CompatAndroid, etc., but there's a lot of code there:

https://developer.mozilla.org/en-US/docs/Template:CompatGeckofxos

I can help, but it may be a few days.

**Comment by trevorhobson** [comment]
It is why I left it off the original list of simple ones.

I just don't understand why the test failed. As far as I understand I have not made anything different to the test_compat_row_cell_support_compatgeckodesktop_bad_text .

It is failing on expected_versions which I am doing nothing with, as far as I know.

**Comment by jwhitlock** [comment]
You are setting version_found to "1.2", but asserting that no version was parsed.

There is code here that isn't reflected in ``CompatGeckoFxOS``, such as Gecko versions for 2.0, 2.1.  Are you sure about this?  Should ``CompatGeckoFxOS`` be updated?  Should it detect non-integer Gecko versions as well?

Here's a more direct translation of ``CompatGeckoFxOS``:

```python
                elif kname == 'compatgeckofxos':
                    gecko_ver = self.unquote(item['args'][0])
                    if gecko_ver.endswith('.0'):
                        gecko_ver = gecko_ver[:-2]
                    try:
                        ngecko_ver = int(gecko_ver)
                    except ValueError:
                        # Not an error in CompatGeckoFxOS?
                        # self.errors.append((
                        #    item['start'], item['end'],
                        #    'Invalid Gecko version "%s"' % gecko_ver))
                        version_found = "1.0"
                    else:
                        if ngecko_ver in range(19, 27):
                            version_found = "1.2"
                        elif ngecko_ver in range(27, 29):
                            version_found = "1.3"
                        elif ngecko_ver in range(29, 31):
                            version_found = "1.4"
                        else:
                            version_found = "1.0"

                        try:
                            override_version = self.unquote(item['args'][1])
                        except IndexError:
                            pass
                        else:
                            version_found = override_version
```

**Comment by trevorhobson** [comment]
> There is code here that isn't reflected in CompatGeckoFxOS, such as Gecko versions for 2.0, 2.1. Are you sure about this?

Yes. On the off chance that someone uses this for a recent release before the scrape and replace is done.

> Should CompatGeckoFxOS be updated?

Possibly, but I hope no. It should probably be deleted, but like others of its kind it is a time issue to remove. The Gecko version is less relevant now that most product version numbers and Gecko version numbers match and the Firefox OS for developers pages link to the Firefox for developers pages it is easier to determine what features are available that it was when the version numbers did not match.

> Should it detect non-integer Gecko versions as well?

I made the assumption that there was a good reason for using a float in the handling of CompatGeckoDesktop, so I copied that. Strictly speaking it should do the same check for low Gecko versions that CompatGeckoDesktop does to make sure that the version is a valid one, but as we do not check against a strict list of valid Gecko versions after 5 in CompatGeckoDesktop and others I don't think the risk is too high here. We have handled incorrect Gecko versions after 5 on MDN by ignoring the decimal, so we treat 5.0.1.4.5.6 as if it was 5.

**Comment by jwhitlock** [comment]
Tests pass now, but with missing branches (`make coverage`).  I'll need tests for the 1.2, 1.3, 1.4, 2.0, and 2.2 branches.

**Comment by trevorhobson** [comment]
Closing to move branch.

**Pull request closed without merging**
