### PR TITLE
bug 1134426

### PR DESCRIPTION
**Pull request by trevorhobson**
- Ignore tags in Browser Compatibility table header

### CODE REVIEW

**Comment by trevorhobson** [comment]
This should fix 'Unknown Browser "<strong>Firefox OS</strong>"'
I really cannot figure out how to make a test for this

**Comment by jwhitlock** [comment]
What are some pages affected by this issue?  That will help me write the tests.

[Bug 1079920](https://bugzilla.mozilla.org/show_bug.cgi?id=1079920) is the "create a process bug", which is submitted for code review.  We'll probably need to file a new bug under [bug 1132269](https://bugzilla.mozilla.org/show_bug.cgi?id=1132269)

**Comment by trevorhobson** [comment]
There are 27 Pages that have the 'Unknown Browser "\<strong>Firefox OS\</strong>"' issue, one being https://developer.mozilla.org/en-US/docs/Web/API/Performance.navigation , https://browsercompat.herokuapp.com/importer/343

**Comment by jwhitlock** [comment]
My preference would be to fix the MDN pages - the bold title is ugly and out of place, and I wish the author would have noticed before copy and pasting over 27 pages.

But, assuming that won't work, I'd prefer adding more fixes to [browser_name_fixes](https://github.com/jwhitlock/web-platform-compat/blob/1079920_import_process/mdn/scrape.py#L825-L832), instead of blindly throwing out HTML:

```python
    browser_name_fixes = {
        'Firefox (Gecko)': 'Firefox',
        'Firefox Mobile (Gecko)': 'Firefox Mobile',
        'Safari (WebKit)': 'Safari',
        'Windows Phone': 'IE Mobile',
        'IE Phone': 'IE Mobile',
        'IE': 'Internet Explorer',
        '<strong>Firefox OS</strong>': 'Firefox OS',
        '<strong>Firefox OS (Gecko)</strong>': 'Firefox OS',
        'Firefox OS (Gecko)': 'Firefox OS',
    }
```

Searching for 'Unknown Browser' on the [errors spreadsheet](https://docs.google.com/spreadsheets/d/1UcSYEoTy_H-T1KIQV-gH50pHzHXqpkm63Kl4XqrILUM/edit#gid=1061636313) might find some other candidates, but once we get into single instances, I'd strongly prefer the MDN fix.

**Comment by trevorhobson** [comment]
If this is all going to be replaced eventually does it matter if we ignore selected bits? The parts we are ignoring are constrained by the th tags so could not be accidentally removing important information. Who knows what other tags may be hiding there that we will uncover as we improve the scraper, this could be a tedious process.

**Comment by jwhitlock** [comment]
That's my hope.  However, replacing the MDN content is not a Q1 deliverable.  If priorities change (which they've threatened to do several times over the last year), this whole project just might end up as a linter for MDN.  In which case, I'd rather be stricter.

**Comment by trevorhobson** [comment]
In my opinion a good linter would identify issues and notify the user, but keep processing the content if possible.

If I was going to make this linter compatible I would compare the string before and after the removed tags and add a lint issue if different, such as "Browser Compatibility table header should not contain tags, ORIGINAL HTML should be replaced with TAGS REMOVED TEXT" or something similar.

Also one would probably want to notify if browser_name_fixes changed the name, something like "ORIGINAL BROWSER NAME should be replaced with FIXED BROWSER NAME". Although you would probably want to split off the ones that contain the engine, as the parser is removing the engine from the content but a linter would just be validating existing content.

**Comment by jwhitlock** [comment]
After some thought (and some extra hours freed up), I'm going a slightly different direction.  I'm going to change the `<th>` grammar rule be more permissive, allowing more attributes and an optional `<strong>` tag.  This will mean the `<strong>` tag gets discarded in the grammar, not in the visitor, and we have visibility into other random tags (`<span>`, etc.) that show up in headers.  My plan is to cover [1134624](https://bugzilla.mozilla.org/show_bug.cgi?id=1134624) as well.  I'll have some code in the next day or so.

**Comment by jwhitlock** [comment]
The code is in the [1132269_more_importer](https://github.com/jwhitlock/web-platform-compat/tree/1132269_more_importer) branch.  There are several changes to get to the point where both specification and compatibility header cells can use the same rules and visitors.  The final changes in commit ac99e31ff.

I'm back to treating the code like an importer rather than a linter, so unknown attributes do not raise issues.

**Comment by jwhitlock** [comment]
Closed due to alternate code in branch [1132269_more_importer](https://github.com/jwhitlock/web-platform-compat/tree/1132269_more_importer)

**Pull request closed without merging**
