### PR TITLE
fix bug 1132694

### PR DESCRIPTION
**Pull request by trevorhobson**
- Allow tags in h2, except Specifications and Compatibility
- Allow tags in th of Specifications table

### CODE REVIEW

**Comment by trevorhobson** [comment]
Sorry made some git mistakes in original pull request.

**Comment by jwhitlock** [comment]
The `<h2>` tag code + tests is good, but I'm not seeing an example of allowing tags in `<th>` that I'm comfortable with.  The closest I found is [Web/API/Window.postMessage](https://browsercompat.herokuapp.com/importer/561), where `<strong>Text</strong>` is used everywhere, which smells like [bug 1134426](https://bugzilla.mozilla.org/show_bug.cgi?id=1134426) instead.

Are you OK with me merging just the `<h2>` portion?  It's in commit 17adc21

**Comment by trevorhobson** [comment]
> Are you OK with me merging just the \<h2\> portion? It's in commit 17adc21
That is fine by me.

**Comment by jwhitlock** [comment]
Closing due to inclusion of code in branch [1132269_more_importer](https://github.com/jwhitlock/web-platform-compat/tree/1132269_more_importer).  `<th><strong>Text</strong></th>` code fixed in ac99e31ff, same branch.

**Pull request closed without merging**
